language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
 - pip install -r requirements.txt
 - pip install -e .

# command to run tests
script:
# matplotlib is only needed in some testing scripts (no real requirement)
 - pip install matplotlib
 - python symbtools/test/test_all.py all
#  install optional dependency
 - pip install control casadi
 - python symbtools/test/test_all.py optdep
