language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
 - pip install -r requirements.txt
 - pip install -e .

# command to run tests
script:
 - python symbtools/test/test_all.py all
#  install optional dependency
 - pip install control casadi
 - python symbtools/test/test_all.py optdep
